
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfvjqmhlkwluxwkkzmpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdmpxbWhsa3dsdXh3a2t6bXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTk1OTIsImV4cCI6MjA2MjI5NTU5Mn0.sjkjCHJk59DZh6t2Ic19CUmmOtUYvlfPcoBlkaaHW_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  },
});
